# Change these first
owner: messiernft
repo: testnet_status

sites:
  - name: Messier.Art Testnet
    url: https://mtestnet.messier.art/
    headers:
      - "Authorization: Basic $BASIC_AUTH"
    icon: https://mtestnet.messier.art/darkMobile.png
  - name: Testnet Indexer
    url: https://dev-server.messier.art/api/indexer_health
    icon: https://mtestnet.messier.art/darkMobile.png
  - name: Testnet API Server
    url: https://dev-server.messier.art/health
    icon: https://mtestnet.messier.art/darkMobile.png
  - name: Messier.Art IPFS
    url: https://ipfs.messier.art/ipfs/Qmf46hrJfcA8TvEMh6VNHM2G4JxsykxfYwcfhRr5ZFT12E
    icon: https://mtestnet.messier.art/darkMobile.png

status-website:
  theme: light
  logoUrl: https://mtestnet.messier.art/darkMobile.png
  name: Messier.Art Status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

assignees:
  - 0xnulll
  
# See https://upptime.js.org/docs/configuration
